baseURL = "https://faruk-guler.github.io/"
languageCode = "en-us"
title = "Faruk Güler"
theme = "hello-friend-ng"   # Tema adını doğru yaz

paginate = 10
enableRobotsTXT = true

[params]
  # Tema ile ilgili parametreler buraya gelir
  defaultTheme = "dark"
