# No "theme = 'PaperMod'" line
baseURL = 'http://faruk-guler.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
